import { Geist, Geist_Mono, Eczar } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Contact from "@/components/Contact";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const getEczar = Eczar({
  variable: "--font-eczar",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${getEczar.variable} antialiased`}
      >
        {children}
        <Contact />
      </body>
    </html>
  );
}
